version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: shacharnaor/hello_world_backend:V1 
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    image: shacharnaor/hello_world_frontend:V1
    container_name: html_frontend
    ports:
      - "8080:80"

volumes:
  postgres_data:
